sudo: true

language:
  - android

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

jdk:
  - oraclejdk8

notifications:
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
    on_success: always
    on_failure: always
    on_start: never
    rooms:
      - eventhubgroup:bC4CN38MLR12layVKbWJhnmX

before_script:
  - echo n | android create avd --force --name test --target android-21 --abi armeabi-v7a --tag default
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell wm dismiss-keyguard

script:
  - ./gradlew test
  - ./gradlew connectedAndroidTest

before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license
